name: deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies for build
      run: pip install --upgrade setuptools wheel

    - name: Get version from setup.py
      id: get-version
      run: echo ::set-output name=version::v`python setup.py -V`

    - name: Get tag
      id: get-tag
      run: echo ::set-output name=tag-name::${GITHUB_REF#refs/tags/}

    - name: Check version mismatch
      run: |
        if [[ "${{ steps.get-version.outputs.version }}" != "${{ steps.get-tag.outputs.tag-name }}" ]]; then
          echo ::error file=setup.py::Version mismatch
          exit 1
        fi

    - name: Build
      run: python setup.py sdist bdist_wheel

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
